### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by mattemoore** [soundtrackyourbrand/sinopia-github-oauth-cli#2]

**Comment by mattemoore** [comment]
I've spent some more time digging into this.  It appears that `index.js` opens a browser pointing to `http://registry/oauth/authorize` which makes a request back to the client on port 8239 which is then consumed by the listener, updates .npmrc, then closes the listener.  

If that is correct then this code as it is written does not work in a non-desktop environment correct?

**Comment by fredr** [comment]
Did you mean to remove the description of your question? 

To answer your original question, yes, you need a browser, as this uses the web flow of github oauth (https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#web-application-flow)

The local webserver is started to handle the callback from sinopia-github-oauth to be able to set the token in your npmrc.
